"""

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qxnQOG-mp-_MGdXC-KTaZ5rVQezqzsCc

Extracting RGB Features with DINOv2
Usage: In Google Colab, go to Runtime → Change Runtime Type → Select GPU(T4)

Prerequisites:
  - You have upload the RGB data into your Google Drive(it contains 4 recording folders, each containing an rgb/ folder)
  - You have uploaded features.csv which is the merge table of motion(gaze,hand and pose) to Google Drive
"""

# CELL 1:Google Drive
from google.colab import drive
drive.mount('/content/drive')

"""Train data"""

import os, numpy as np, pandas as pd, torch, time
from torchvision import transforms
from PIL import Image

CSV_PATH = "/content/drive/MyDrive/XR-rbg/merge.csv" # The features from motion modality, which are obtained from Merge_data.py
RGB_ROOT = "/content/drive/MyDrive/XR-rbg/partA_rbg" # The RGB iamge
OUT_CSV  = "/content/drive/MyDrive/XR-rbg/dinov2_feats.csv" # The output path
IMG_SIZE = 224
BATCH    = 64

device = "cuda" if torch.cuda.is_available() else "cpu"
model = torch.hub.load("facebookresearch/dinov2", "dinov2_vits14", trust_repo=True).to(device).eval()
tf = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225]),
])

feat = pd.read_csv(CSV_PATH)
# Collect the image paths corresponding to the frames in features.csv
items = []
for _, r in feat[["recording_id","frame"]].iterrows():
    p = os.path.join(RGB_ROOT, str(r["recording_id"]), str(r["frame"]))
    if os.path.exists(p):
        items.append((r["recording_id"], r["frame"], p))
print(f"{len(items)} images, and (features.csv has {len(feat)} frame)")

rows, bmeta, bimg = [], [], []
def flush():
    if not bimg: return
    x = torch.stack(bimg).to(device)
    with torch.no_grad():
        emb = model(x).cpu().numpy()
    for (rec, fr), e in zip(bmeta, emb):
        rows.append([rec, fr] + e.tolist())
    bmeta.clear(); bimg.clear()

t = time.time()
for i, (rec, fr, p) in enumerate(items):
    bmeta.append((rec, fr)); bimg.append(tf(Image.open(p).convert("RGB")))
    if len(bimg) >= BATCH: flush()
    if i % 1000 == 0: print(f"  {i}/{len(items)}  ({time.time()-t:.0f}s)")
flush()

cols = ["recording_id","frame"] + [f"img_{j}" for j in range(len(rows[0])-2)]
pd.DataFrame(rows, columns=cols).to_csv(OUT_CSV, index=False)
print(f"Save {len(rows)}  x {len(cols)-2}  → {OUT_CSV}  (Total time: {time.time()-t:.0f}s)")

"""Test data"""

import os, numpy as np, pandas as pd, torch, time
from torchvision import transforms
from PIL import Image

CSV_PATH = "/content/drive/MyDrive/XR-rbg/test.csv"
RGB_ROOT = "/content/drive/MyDrive/XR-rbg/test"
OUT_CSV  = "/content/drive/MyDrive/XR-rbg/dinov2_feats_test.csv"
IMG_SIZE = 224
BATCH    = 64

device = "cuda" if torch.cuda.is_available() else "cpu"
model = torch.hub.load("facebookresearch/dinov2", "dinov2_vits14", trust_repo=True).to(device).eval()
tf = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225]),
])

feat = pd.read_csv(CSV_PATH)

items = []
for _, r in feat[["recording_id","frame"]].iterrows():
    p = os.path.join(RGB_ROOT, str(r["recording_id"]), str(r["frame"]))
    if os.path.exists(p):
        items.append((r["recording_id"], r["frame"], p))
print(f"{len(items)} images, and (features.csv has {len(feat)} frame)")


rows, bmeta, bimg = [], [], []
def flush():
    if not bimg: return
    x = torch.stack(bimg).to(device)
    with torch.no_grad():
        emb = model(x).cpu().numpy()
    for (rec, fr), e in zip(bmeta, emb):
        rows.append([rec, fr] + e.tolist())
    bmeta.clear(); bimg.clear()

t = time.time()
for i, (rec, fr, p) in enumerate(items):
    bmeta.append((rec, fr)); bimg.append(tf(Image.open(p).convert("RGB")))
    if len(bimg) >= BATCH: flush()
    if i % 1000 == 0: print(f"  {i}/{len(items)}  ({time.time()-t:.0f}s)")
flush()

cols = ["recording_id","frame"] + [f"img_{j}" for j in range(len(rows[0])-2)]
pd.DataFrame(rows, columns=cols).to_csv(OUT_CSV, index=False)
print(f"Save {len(rows)}  x {len(cols)-2}  → {OUT_CSV}  (Total time: {time.time()-t:.0f}s)")
